PythonLayer:
  Type: "AWS::Lambda::LayerVersion"
  Properties:
    CompatibleRuntimes: 
      - python3.6
      - python3.7
    Content: 
      S3Bucket: ecr-continuous-scan-generate-findings
      S3Key: Python-Boto3-f551171d-25b9-4222-b075-e21dbaa9e101.zip
    Description: My layer
    LayerName: my-layer
    LicenseInfo: MIT
