AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  generateecrfindingslambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./generate-ecr-findings-lambda-9ae0010e-3e9f-4458-bfa8-4cb28cf3be8e.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::215745394840:role/service-role/myrole'
      Layers:
        - 'arn:aws:lambda:us-east-1:215745394840:layer:Python-Boto3:1'
